name: Build and Deploy

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때 트리거

jobs:
  build:
    runs-on: windows-latest  # Windows 환경에서 실행

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  # 사용 중인 .NET 버전

    - name: Build project
      run: |
        cd DockerWinformTEST  # 솔루션 파일이 있는 디렉토리로 이동
        dotnet build DockerWinformTEST.sln --configuration Release

    - name: Deploy
      shell: cmd
      run: |
        @echo off
        set FTP_HOST=ftpupload.net
        set FTP_USER=if0_38215116
        set FTP_PASS=BtBLgJuTb2AeMS 
        set LOCAL_PATH=DockerWinformTEST\DockerWinformTEST\bin\Release

        echo open %FTP_HOST%> ftp.txt
        echo %FTP_USER%>> ftp.txt
        echo %FTP_PASS%>> ftp.txt
        echo mput %LOCAL_PATH%\*>> ftp.txt
        echo bye>> ftp.txt

        ftp -s:ftp.txt